import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>{process.env.TEST_VAR}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">{process.env.READ_VARIABLE_TOKEN}</a>
          Welcome to <a href="https://nextjs.org">{process.env.TEST_VAR}</a>
        </h1>
      </main>
    </div>
  );
}
